# Site settings
title: 如禅的博客
description: "如禅的技术成长博客 ..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://ruchanya.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: 如禅
user_title: Lorem Ipsum - FrontEnd
email: 1351187492@qq.com
twitter_username: loremipsum
github_username:  ruchanya
gplus_username:  loremipsum
disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: 首页
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: 标签
    url: /tags
  - title: 关于我
    url: /about
# projects in header index
projects:
  - name: 暂无
    url: 
  - name: 暂无
    url: 
  - name: 暂无
    url: 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
